# Generated by Django 5.2.4 on 2026-04-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperorder",
            name="realized_pnl",
            field=models.FloatField(default=0),
        ),
    ]
